{% set name = "deodr" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bff2d5036a74900c7dbc9a5284e99935fcf995f9798cee5e3e583b598501d58f
  # patches:
  #   # Currently the required CXX file for build isn't packaged in the release, so generated here.
  #   - setup_CXX.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36 or win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython
    - numpy
    - scipy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - deodr

about:
  home: https://github.com/martinResearch/DEODR/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: DEODR (for Discontinuity-Edge-Overdraw based Differentiable Renderer) is a differentiable 3D mesh renderer written in C with Python and Matlab bindings.
  dev_url: https://github.com/martinResearch/DEODR/

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - oblute
    - rluria14
